name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SECRET }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no root@188.246.226.238 "
            cd /var/www/ratkevich-api &&
            git fetch --all &&
            git reset --hard origin/main &&
            echo 'CLIENT_ID=${{ secrets.CLIENT_ID }}' > .env &&
            echo 'AUTHORIZATION_KEY=${{ secrets.AUTHORIZATION_KEY }}' >> .env &&
            echo 'SCOPE=${{ secrets.SCOPE }}' >> .env &&
            python3 -m venv venv &&  # Создание виртуального окружения
            source venv/bin/activate &&  # Активация виртуального окружения
            pip install fastapi uvicorn &&  # Установка зависимостей
            pm2 start python --name ratkevich-api -- main.py  # Запуск через PM2
          "